[package]
name = "lsp-for-freemarker"
version = "0.1.1"
authors = ["Lu Kai <kai.f.lu@nokia.com>"]
description = "A Freemarker Language Server implemented in Rust"
publish = false

edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "lsp-for-freemarker"

[dependencies]
tree-sitter-freemarker = { path = "../parser/tree-sitter-freemarker" }

ropey = "1.6"
rust-embed = { version = "8.12", features = ["include-exclude"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.27"
strum_macros = "0.27"
thiserror = "2.0"
tokio = { version = "1.37", features = ["full"] }
toml = "0.9"
tower-lsp-server = "0.23"
tree-sitter = "0.25"
