identifier = "filter"
category = "built-in"
markdown = """
# filter
---
> category: [Built-ins for sequences](https://freemarker.apache.org/docs/ref_builtins_sequence.html#ref_builtin_filter)
---
> __Note:__
> This built-in is available since FreeMarker 2.3.29.

Returns a new sequence that only contains the elements for which the parameter condition (the predicate) returns `true`.

```template
<#assign xs = [1, -2, 3, 4, -5]>
Positives: <#list xs?filter(x -> x > 0) as x>${x} </#list>
```
Output:
```output
Positives: 1 3 4
```
The predicate can be a lambda expression, a function, or a method with a single argument that returns boolean.

See also: `take_while`, `drop_while`
"""
