identifier = "has_api"
category = "built-in"
markdown = """
# has_api
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_buitin_api_and_has_api)
---
> __Note:__
> This built-in exists since FreeMarker 2.3.22.

Whether a value supports `?api` can be checked like `value?has_api`, which returns a boolean value. Note that the result of `?has_api` isn't influenced by the `api_builtin_enabled` setting.
"""
