identifier = "is_collection"
category = "built-in"
markdown = """
# is_collection
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_isType)
---
Returns `true` if the value is a collection (including extended collection).
"""
