identifier = "is_datetime"
category = "built-in"
markdown = """
# is_datetime
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_isType)
---
Returns `true` if the value is a date-time (contains both year-month-day and time of the day).
"""
