identifier = "is_hash_ex"
category = "built-in"
markdown = """
# is_hash_ex
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_isType)
---
Returns `true` if the value is an extended hash (supports `?keys` and `?values`).
"""
