identifier = "is_number"
category = "built-in"
markdown = """
# is_number
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_isType)
---
Returns `true` if the value is a number.
"""
