identifier = "keep_before_last"
category = "built-in"
markdown = """
# keep_before_last
---
> category: [Built-ins for strings](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_keep_before_last)
---
> __Note:__
> This built-in is available since FreeMarker 2.3.22.

Same as `keep_before`, but keeps the part before the *last* occurrence of the parameter, rather than before the first. Example:
```template
${"foo.bar.txt"?keep_before_last(".")}
```
Output:
```output
foo.bar
```
"""
