identifier = "length"
category = "built-in"
markdown = """
# length
---
> category: [Built-ins for strings](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_length)
---
The number of characters in the string.
"""
