identifier = "remove_beginning"
category = "built-in"
markdown = """
# remove_beginning
---
> category: [Built-ins for strings](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_remove_beginning)
---
> __Note:__
> This built-in is available since FreeMarker 2.3.21.

Removes the parameter substring from the beginning of the string, or returns the original string if it doesn't start with the parameter substring. For example:
```template
${"abcdef"?remove_beginning("abc")}
${"foobar"?remove_beginning("abc")}
```
Output:
```output
def
foobar
```
"""
