identifier = "take_while"
category = "built-in"
markdown = """
# take_while
---
> category: [Built-ins for sequences](https://freemarker.apache.org/docs/ref_builtins_sequence.html#ref_builtin_take_while)
---
> __Note:__
> This built-in is available since FreeMarker 2.3.29.

Returns a sequence that only contains the elements of the input sequence which are *before* the first element that doesn't match the parameter predicate.

```template
<#assign xs = [1, 2, -3, 4, -5, 6]>
<#list xs?take_while(x -> x > 0) as x>${x} </#list>
```
Output:
```output
1 2
```

See also: `drop_while`, `filter`
"""
